version: "3.8"
services:
  db:
    container_name: postgres
    build:
      context: .
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - './queries:/queries'
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    user: "${UID}:${GID}"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: changeme
    volumes:
      - './queries:/var/lib/pgadmin/storage/admin_admin.com/queries'
      - './backups:/var/lib/pgadmin/storage/admin_admin.com/backups'
